### ISSUE TITLE
jsonlog-cli: Config must exist.

### ISSUE THREAD

**Issue by lschmelzeisen** [borntyping/jsonlog#3]
While in `config.py` there is the following:

```python
class Config:
    def load(self, path: typing.Union[None, str, pathlib.Path]) -> None:
        log.info("Loading configuration from file", extra={"path": repr(path)})
        if path is None:
            log.info("Path is none, not loading anything")
            return
         ...
```

This `if` is never triggered. Instead if no config file exists (or it exists and is empty) running `jsonlog` will always give the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lukas/.cache/pypoetry/virtualenvs/jsonlog-cli-dC2_Bh__-py3.6/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lukas/repos/jsonlog/jsonlog-cli/jsonlog_cli/cli.py", line 50, in main
    ctx.obj.load(config_path)
  File "/home/lukas/repos/jsonlog/jsonlog-cli/jsonlog_cli/config.py", line 94, in load
    instance = json.loads(p.read_text(encoding="utf-8"))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

Manually creating a config file only containing `{}` makes everything work as expected, but this is probably not the intended behavior.

**Comment by borntyping** [comment]
Fixed in jsonlog-cli 5.2.0.
