### ISSUE TITLE
multiline_keys can not be used in config.

### ISSUE THREAD

**Issue by lschmelzeisen** [borntyping/jsonlog#5]
Since you mentioned these bug reports to be helpful, I figured I keep submitting whenever I spot something. Today, I tried to use `multiline_keys` as documented in your updated Readme.

Config file:
```json
{
    "templates": {
        "default": {
            "format": "{timestamp} {message}",
            "multiline_keys": ["traceback"]
        }
    }
}
```

I then received the following error:
```
$ jsonlog template docs/example.log 
Traceback (most recent call last):
  File "/home/lukas/repos/nasty-analysis/.venv/bin/jsonlog", line 8, in <module>
    sys.exit(main())
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/cli.py", line 96, in template_formatter
    handler.consume(streams)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/stream.py", line 134, in consume
    self.consume_stream(stream)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/stream.py", line 138, in consume_stream
    self.echo(line, data)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/stream.py", line 158, in echo
    self.echo_out(line, data)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/stream.py", line 166, in echo_out
    output = self.formatter.format_record(record)
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/pattern.py", line 31, in format_record
    blocks: typing.Tuple[str, ...] = tuple(self.format_multiline(record))
  File "/home/lukas/repos/nasty-analysis/.venv/lib/python3.6/site-packages/jsonlog_cli/pattern.py", line 45, in format_multiline
    value = record.extract(key.name)
AttributeError: 'str' object has no attribute 'name'
```

I figure the problem is somehow connected to `Key.from_string/s()` not being called from `Config.read()`, respectively the `KeyValuePattern` and `TemplatePattern` constructors. When specifying this on the CLI via `--multiline-key traceback` it works as expected.

Side node: I'm not if the example of a `defaults` pattern in the example config file in the Readme is intentional. Using `default` as the pattern name instead does what I expected, i.e., being applied by default without any command line arguments.

Another side node: I couldn't figure out what `multiline_json` is supposed to do / does.

**Comment by borntyping** [comment]
jsonlog-cli 6.0.0 replaces the config loading entirely (using pydantic, which also removes the dependency on `dataclasses`), making it a lot more reliable for nested objects.

Documentation around `default` has been added, and the example has been made a bit clearer, plus a note on what `multiline_json` does (it didn't actually do anything, but that wasn't intentional - it should switch between two parsing modes for incoming data).

Thanks!
