### ISSUE TITLE
Config does not seem to be applied.

### ISSUE THREAD

**Issue by lschmelzeisen** [borntyping/jsonlog#6]
Hey, sorry, that it took me a while do file this issue. I noticed something was wrong relatively quickly after your last update, but didn't find the time to do this until now.

When taking the example config from the Readme I spotted some problems which I think boil down to the config file not being correctly applied.

For reference, the config file `~/.config/jsonlog/config.json` is:

```json
{
  "keyvalues": {
    "basic": {
      "priority_keys": ["timestamp", "message"]
    },
    "comprehensive": {
      "level_key": "level",
      "multiline_json": false,
      "multiline_keys": [],
      "priority_keys": [],
      "removed_keys": []
    }
  },
  "templates": {
    "basic": {
      "format": "{timestamp} {message}"
    },
    "comprehensive": {
      "level_key": "level",
      "multiline_json": false,
      "multiline_keys": [],
      "format": "{timestamp} {message}"
    }
  }
}
```

According to `jsonlog kv --help` the option `priority_keys` should "Set keys to output first" (no description of this in the doc). However, I receive the following output:

```
$ jsonlog kv -p basic docs/example.log 
timestamp='2019-06-25T17:00:56.929526' name='example' message='debug level log message'
timestamp='2019-06-25T17:00:56.929690' name='example' message='info level log message'
timestamp='2019-06-25T17:00:56.929761' name='example' message='warning level log message'
timestamp='2019-06-25T17:00:56.929819' name='example' message='error level log message'
timestamp='2019-06-25T17:00:56.929877' name='example' message='error level log message with traceback' traceback='Traceback (most recent call last):\n  File "docs/example.py", line 15, in <module>\n    1 / 0\nZeroDivisionError: division by zero'
timestamp='2019-06-25T17:00:56.930077' name='example' message='critical level log message'
```

I expected the `priority_keys` field in the config to move the `timestamp` and  `messages` field to the front of the line, but could not observe any change.

Additionally, and perhaps more severely, it does not seem to be possible to use the configured `templates`:

```
$ jsonlog template -t basic ~/repos/jsonlog-untouched/jsonlog-cli/docs/example.log 
Traceback (most recent call last):
  File "/home/lukas/test-alive-progress/.venv/bin/jsonlog", line 10, in <module>
    sys.exit(main())
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/lukas/test-alive-progress/.venv/lib/python3.8/site-packages/jsonlog_cli/cli.py", line 90, in template_formatter
    template: jsonlog_cli.pattern.TemplatePattern = config.templates[template_name]
KeyError: 'basic'
```

Is this a (new) bug, or did I misunderstand something?

By the way, I run into the following very often and would appreciate if you could add an shortopt-alias for `--help` 😅 (and maybe even aliases like `jsonlog t` for `jsonlog template`, etc.):
```
$ jsonlog -h
Usage: jsonlog [OPTIONS] COMMAND [ARGS]...
Try 'jsonlog --help' for help.

Error: no such option: -h
```

**Comment by borntyping** [comment]
These are bugs - I'll take a look.

**Comment by borntyping** [comment]
These three things should all be fixed now.

* Config loading was overridden by empty options.
* Template loading was broken.
* Short -h help option added.

Thanks once again for the help!

**Comment by lschmelzeisen** [comment]
Great, thank you very much for the quick fix! Especially the aliases are great!

One more oddity, that I just noticed but that doesn't bother me too much is that the following config file is not accepted:

```json
{
  "templates": {
    "basic": {
      "format": "{timestamp} {message}"
    }
  }
}
```

and results in the following error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Config
keyvalues
  field required (type=value_error.missing)
```

whereas this one is fine:

```json
{
  "keyvalues": {
  },
  "templates": {
    "basic": {
      "format": "{timestamp} {message}"
    }
  }
}
```

**Comment by borntyping** [comment]
Pushed a quick fix for that - just needed defaults to be defined for those fields.

https://github.com/borntyping/jsonlog/commit/b9c178baf6c8b5de18b9a98afbbc9ea4ac7554c7
