### ISSUE TITLE
Running with a configured template pattern fails.

### ISSUE THREAD

**Issue by lschmelzeisen** [borntyping/jsonlog#7]
With the config example from the README, trying to use a configured template pattern currently fails:

```
$ jsonlog template --template basic docs/example.log 
Traceback (most recent call last):
  File "/home/lukas/test-jsonlog/.venv/bin/jsonlog", line 10, in <module>
    sys.exit(main())
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/lukas/test-jsonlog/.venv/lib/python3.8/site-packages/jsonlog_cli/cli.py", line 198, in format_template
    template = template.replace(format=template_format)
AttributeError: 'dict' object has no attribute 'replace'
```

This seems to be a regression introduced in jsonlog-cli 6.1.2, because it works as expected in 6.1.1.

**Comment by borntyping** [comment]
I don't seem to be able to recreate this.

**Comment by lschmelzeisen** [comment]
Steps to reproduce:

```
$ docker run -it python:3.8 bash
root@289e4db5fa76:/# pip install jsonlog-cli
root@289e4db5fa76:/# mkdir -p ~/.config/jsonlog
root@289e4db5fa76:/# cat > ~/.config/jsonlog/config.json <<EOL
{
  "keyvalues": {
    "basic": {
      "priority_keys": ["timestamp", "message"]
    },
    "comprehensive": {
      "level_key": "level",
      "multiline_json": false,
      "multiline_keys": [],
      "priority_keys": [],
      "removed_keys": []
    }
  },
  "templates": {
    "basic": {
      "format": "{timestamp} {message}"
    },
    "comprehensive": {
      "level_key": "level",
      "multiline_json": false,
      "multiline_keys": [],
      "format": "{timestamp} {message}" 
    }
  }
}
EOL
root@289e4db5fa76:/# wget https://raw.githubusercontent.com/borntyping/jsonlog/master/jsonlog-cli/docs/example.log
root@289e4db5fa76:/# jsonlog template --template basic example.log 
```

Done with Docker so that it should be platform agnostic, but should probably work similar in a venv.

**Comment by borntyping** [comment]
Seems Pydantic updated and I was still using an older version. Not sure what changed to break this.

**Comment by borntyping** [comment]
Pushed a version that avoids Pydantic 1.6 for now.
